"""
tts_engine.py  -  Indonesian TTS with pre-cached audio files.

Strategy (in priority order):
  1. Play a pre-cached .mp3 file (generated by gTTS at first run)
     → Fast, offline after first internet connection, native Indonesian voice
  2. gTTS online (if cache miss and internet available)
     → Full Indonesian voice, requires internet
  3. pyttsx3 (offline) with Indonesian voice if installed
     → May sound English on systems without Indonesian SAPI voice
  4. Console print  (always available)
"""

import os
import threading
import subprocess

_CACHE_DIR = os.path.join(os.path.dirname(__file__), "audio_cache")
_backend: str = "console"
_pygame_ok: bool = False
_pyttsx3_engine = None

# Fixed output phrases - pre-generate these for best UX
_FIXED_PHRASES = [
    "Seratus Ribu Rupiah, Asli",
    "Lima Puluh Ribu Rupiah, Asli",
    "Dua Puluh Ribu Rupiah, Asli",
    "Sepuluh Ribu Rupiah, Asli",
    "Lima Ribu Rupiah, Asli",
    "Dua Ribu Rupiah, Asli",
    "Seribu Rupiah, Asli",
    "Seratus Ribu Rupiah, Mencurigakan atau Palsu",
    "Lima Puluh Ribu Rupiah, Mencurigakan atau Palsu",
    "Dua Puluh Ribu Rupiah, Mencurigakan atau Palsu",
    "Sepuluh Ribu Rupiah, Mencurigakan atau Palsu",
    "Lima Ribu Rupiah, Mencurigakan atau Palsu",
    "Dua Ribu Rupiah, Mencurigakan atau Palsu",
    "Seribu Rupiah, Mencurigakan atau Palsu",
    "Uang Tidak Dikenali atau Palsu",
    "Uang Tidak Terlihat, Dekatkan Kamera",
    "Posisi Tidak Terbaca, Coba Lagi",
    "Sistem siap memindai",
    "Memproses",
]


def _phrase_to_filename(text: str) -> str:
    """Convert a phrase to a safe cache filename."""
    safe = text.lower()
    for ch in " ,./\\:":
        safe = safe.replace(ch, "_")
    return os.path.join(_CACHE_DIR, f"{safe}.mp3")


def _try_init_pygame() -> bool:
    global _pygame_ok
    try:
        import pygame
        pygame.mixer.init()
        _pygame_ok = True
        return True
    except Exception:
        return False


def _try_init_pyttsx3():
    global _pyttsx3_engine
    try:
        import pyttsx3
        eng = pyttsx3.init()
        eng.setProperty("rate", 130)
        # Look for an Indonesian voice
        for voice in eng.getProperty("voices"):
            vid = voice.id.lower()
            vname = voice.name.lower()
            if "id" in vid or "indonesia" in vname or "indonesian" in vname:
                eng.setProperty("voice", voice.id)
                print(f"[TTS] Indonesian voice found: {voice.name}")
                break
        _pyttsx3_engine = eng
        return True
    except Exception:
        return False


def _generate_cache(text: str) -> str | None:
    """Try to generate and cache an mp3 for `text` via gTTS. Returns path or None."""
    try:
        from gtts import gTTS
        path = _phrase_to_filename(text)
        if not os.path.exists(path):
            gTTS(text=text, lang="id", slow=False).save(path)
        return path
    except Exception:
        return None


def _build_cache_async():
    """Background thread: pre-generate all fixed phrases."""
    os.makedirs(_CACHE_DIR, exist_ok=True)
    for phrase in _FIXED_PHRASES:
        path = _phrase_to_filename(phrase)
        if not os.path.exists(path):
            _generate_cache(phrase)


def init() -> None:
    global _backend

    os.makedirs(_CACHE_DIR, exist_ok=True)

    _try_init_pygame()

    # Attempt to pre-build the audio cache (requires internet, runs in background)
    threading.Thread(target=_build_cache_async, daemon=True).start()

    # Determine runtime backend
    if _pygame_ok:
        # Check if gTTS is importable (needed for cache misses)
        try:
            import gtts  # noqa: F401
            _backend = "gtts_cached"
            print("[TTS] Backend: gTTS + pygame (Indonesian, cache-first)")
        except ImportError:
            # pygame only - can play cached files, no fallback for new phrases
            if os.listdir(_CACHE_DIR):
                _backend = "pygame_only"
                print("[TTS] Backend: pygame (cached audio only)")
            else:
                # No gTTS and no cache: fall through to pyttsx3
                _backend = "console"
    
    if _backend == "console":
        if _try_init_pyttsx3():
            _backend = "pyttsx3"
            print("[TTS] Backend: pyttsx3")
        else:
            print("[TTS] Backend: console (no audio)")


def speak(text: str) -> None:
    print(f"[TTS] {text}")
    threading.Thread(target=_speak_async, args=(text,), daemon=True).start()


def _play_mp3(path: str) -> bool:
    if not _pygame_ok:
        return False
    try:
        import pygame
        pygame.mixer.music.load(path)
        pygame.mixer.music.play()
        while pygame.mixer.music.get_busy():
            import time; time.sleep(0.05)
        return True
    except Exception as exc:
        print(f"[TTS] pygame error: {exc}")
        return False


def _speak_async(text: str) -> None:
    # 1. Try cached mp3
    cached_path = _phrase_to_filename(text)
    if os.path.exists(cached_path) and _pygame_ok:
        if _play_mp3(cached_path):
            return

    # 2. Generate on the fly (gTTS) and cache
    if _backend in ("gtts_cached",):
        path = _generate_cache(text)
        if path and _play_mp3(path):
            return

    # 3. pyttsx3 fallback
    if _pyttsx3_engine is not None:
        try:
            _pyttsx3_engine.say(text)
            _pyttsx3_engine.runAndWait()
            return
        except Exception as exc:
            print(f"[TTS] pyttsx3 error: {exc}")

    # 4. Console only (already printed above in speak())